# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Cache .import
        uses: actions/cache@v3.0.11
        with:
          path: $GITHUB_WORKSPACE/godot-project/.import
          key: ${{ runner.os }}-godot-import-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-godot-import-
      - name: Import assets into project
      # Se hace dos veces, en la primera van a fallar los elementos que necesitan que otros se carguen primero (las escenas con scripts de post import)
        run: |
          cd $GITHUB_WORKSPACE/godot-project
          godot -e --export-pack lightweight ./assets/icon.png
          godot -e --export-pack lightweight ./assets/icon.png

